<?php
/**
 * Created by PhpStorm.
 * User: zhaozhiliang
 * Date: 2019/1/10
 * Time: 上午12:43
 */

namespace app\model;

use core\lib\model2;
class goodsModel extends model2
{
    public $table = 'goods';
    public function lists(){
        $ret = $this->select($this->table, "*");
        return $ret;
    }

    public function getOne($id){
        $ret = $this->get($this->table, '*', array('id'=> $id));
        return $ret;
    }

    public function setOne($id, $data)
    {
        return $this->update($this->table, $data, array('id'=> $id));
    }

    public function delOne($id)
    {
        return $this->delete($this->table,array('id'=> $id));
    }

    public function insert($table, $datas)
    {
        return parent::insert($table, $datas); // TODO: Change the autogenerated stub
    }
}